[package]
name = "oxide"
version = "0.1.0"
authors = ["Sachin Beniwal <sachinbeniwal0101@gmail.com>"]
edition = "2021"

[dependencies]
eframe = "0.27.2"
nix = { version = "0.29.0", default_featues = false, features = ["process", "term"] }
